apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-account-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: terraform-account
  namespace: terraform-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-account-secret
  namespace: terraform-namespace
  annotations:
    kubernetes.io/service-account.name: terraform-account
type: kubernetes.io/service-account-token
