apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  servers.json: |
    {
        "Servers": {
          "1": {
            "Name": "db PostgreSQL DB",
            "Group": "Servers",
            "Port": 5432,
            "Username": "admin",
            "Host": "postgres",
            "SSLMode": "prefer",
            "MaintenanceDB": "db"
          }
        }
    }