#!/bin/bash -e

export TF_VAR_k8s_host
TF_VAR_k8s_host=$(kubectl config view -o jsonpath="{.clusters[?(@.name==\"$(kubectl config current-context)\")].cluster.server}")

export TF_VAR_k8s_token
TF_VAR_k8s_token=$(kubectl get secret -n terraform-namespace "$(kubectl -n terraform-namespace get serviceaccount terraform-account -o jsonpath='{.secrets[0].name}')" -o jsonpath='{.data.token}' | base64 --decode)

export TF_VAR_k8s_cluster_ca_certificate
TF_VAR_k8s_cluster_ca_certificate=$(kubectl config view --raw -o jsonpath="{.clusters[?(@.name==\"$(kubectl config current-context)\")].cluster.certificate-authority-data}" | base64 --decode)

terraform "$@"
